### ISSUE TITLE
File Saving and Opening

### ISSUE THREAD

**Issue by mfansler** [MillersvilleCS/pumlbuilder#17]
The application should be able to save and open uml documents.

We may want to additionally include an ability to import/export in format that other UML editing applications support.

**Comment by kevincfisher** [comment]
Will facilitate saving using the Externalizable interface

**Comment by kevincfisher** [comment]
Basic single object save/load implemented.

**Comment by kevincfisher** [comment]
Entire document can now be saved/loaded in
