### ISSUE TITLE
Exporting as image files

### ISSUE THREAD

**Issue by kevincfisher** [MillersvilleCS/pumlbuilder#37]
Hey we need to export these documents as .jpg, .png, .svg. uml, .pdf, .omg, .wtf

**Comment by mfansler** [comment]
This could be useful for this purpose: [javafx.scene.Node.snapshot()](http://docs.oracle.com/javafx/2/api/javafx/scene/Node.html#snapshot%28javafx.scene.SnapshotParameters, javafx.scene.image.WritableImage%29)

**Comment by kevincfisher** [comment]
Implemented exporting as .png, printing as a .pdf. Other options were unable to be implemented, may be revisited at a later date
