### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by jwakefield21** [MillersvilleCS/pumlbuilder#57]
All buttons should have a keyboard shortcut associated with them so that the user can use the shortcut instead of having to constantly click on the buttons.

**Comment by kevincfisher** [comment]
links to issue #28

**Comment by kevincfisher** [comment]
Keyboard shortcuts can be added to menu items using the setAccelerator() function

**Comment by kevincfisher** [comment]
Keyboard Shortbuts have been implemented for all relevant 2nd iteration operations (Save/Open/Exit)

**Comment by kevincfisher** [comment]
keyboard shortcuts\* hey I'm dumb
