### ISSUE TITLE
Snarky Error messages

### ISSUE THREAD

**Issue by kevincfisher** [MillersvilleCS/pumlbuilder#59]
It's not rocket science guys...

**Comment by kevincfisher** [comment]
see issue #58

**Comment by mfansler** [comment]
JDK 8u40 is now available, which provides simple Dialog box and Alert box controls, which could be useful for this.  See [JDK 8u40 release blog entry](https://blogs.oracle.com/thejavatutorials/entry/jdk_8u40_released).
